version: '3'

services:
  web:
    build: .
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy


  db:
    image: postgres:alpine
    volumes:
      # binds to local directory maybe
      - ~/apps/postgres:/var/lib/postgresql/data
    
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
       #this ENV variable is only required for the healthcheck section - if you don't specify it, the check command will fail stating the root user doesn't exist in posgres
      PGUSER: "postgres"
    healthcheck:
      #CHANGE 1: this command checks if the database is ready, right on the source db server
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 5s
      timeout: 5s
      retries: 5